/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.Opcion;
import Models.Pregunta;
import Models.Prueba;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Esteban
 */
public class AplicarPruebaPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Prueba prueba;
    private int indiceActual = 0;
    private List<String> respuestasUsuario = new ArrayList<>();
    private ButtonGroup grupoOpciones;

    /**
     * Creates new form AplicarPruebaPanel
     */
    public AplicarPruebaPanel(MainFrame mainFrame, Prueba prueba) {
        this.mainFrame = mainFrame;
        this.prueba = prueba;

        initComponents();
        panelOpciones.setLayout(new BoxLayout(panelOpciones, BoxLayout.Y_AXIS));
        mostrarPregunta(0);
    }

    private void mostrarPregunta(int indice) {
        this.indiceActual = indice;

        Pregunta pregunta = prueba.getPreguntas().get(indice);
        enunciado.setText((indice + 1) + ". " + pregunta.getEnunciado());

        // Limpiar panel y grupo anterior
        panelOpciones.removeAll();
        grupoOpciones = new ButtonGroup();

        for (Opcion o : pregunta.getOpciones()) {
            JRadioButton rb = new JRadioButton(o.getTexto());

            // REGISTRA EVENTO para habilitar el botón "Siguiente"
            rb.addActionListener(e -> btnSiguiente.setEnabled(true));

            grupoOpciones.add(rb);
            panelOpciones.add(rb);

            // Restaurar selección si ya respondió antes
            if (respuestasUsuario.size() > indice && respuestasUsuario.get(indice).equals(o.getTexto())) {
                rb.setSelected(true);
            }
        }

        panelOpciones.revalidate();
        panelOpciones.repaint();

        btnAnterior.setEnabled(indice > 0);
        btnAnterior.setText("Anterior");
        btnSiguiente.setEnabled(false);
        btnSiguiente.setText((indice == prueba.getPreguntas().size() - 1) ? "Finalizar" : "Siguiente");
    }

    private void guardarRespuestaActual() {
        for (Component c : panelOpciones.getComponents()) {
            if (c instanceof JRadioButton rb && rb.isSelected()) {
                if (respuestasUsuario.size() > indiceActual) {
                    respuestasUsuario.set(indiceActual, rb.getText());
                } else {
                    respuestasUsuario.add(rb.getText());
                }
                return;
            }
        }
        // Si no seleccionó nada
        if (respuestasUsuario.size() <= indiceActual) {
            respuestasUsuario.add("");
        }
    }

    private void finalizarPrueba() {
        guardarRespuestaActual();

        int correctas = 0;
        for (int i = 0; i < prueba.getPreguntas().size(); i++) {
            Pregunta pregunta = prueba.getPreguntas().get(i);
            String resp = respuestasUsuario.get(i);

            for (Opcion o : pregunta.getOpciones()) {
                if (o.isEsCorrecta() && o.getTexto().equals(resp)) {
                    correctas++;
                }
            }
        }

        double nota = ((correctas * 6.0) / prueba.getPreguntas().size()) + 1;

        ResultadoPanel resultado = new ResultadoPanel(mainFrame, prueba, respuestasUsuario, nota);
        mainFrame.getMainPanel().add(resultado, "resultado");
        mainFrame.mostrarVista("resultado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enunciado = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        enunciado.setText("jLabel1");

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        btnAnterior.setText("jButton1");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("jButton2");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enunciado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(enunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        guardarRespuestaActual();
        mostrarPregunta(indiceActual - 1);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        guardarRespuestaActual();

        if (indiceActual == prueba.getPreguntas().size() - 1) {
            finalizarPrueba();
        } else {
            mostrarPregunta(indiceActual + 1);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel enunciado;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables
}
