/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.Prueba;
import javax.swing.JOptionPane;

/**
 *
 * @author Esteban
 */
public class CrearPruebaPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Prueba prueba;

    /**
     * Creates new form CrearPruebaPanel
     */
    public CrearPruebaPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        prueba = new Prueba();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombrePrueba = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarPregunta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        txtNombrePrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePruebaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre prueba");

        btnAgregarPregunta.setText("Agregar preguntas");
        btnAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPreguntaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNombrePrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(btnAgregarPregunta)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPregunta)
                    .addComponent(btnSalir))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePruebaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePruebaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        mainFrame.mostrarVista("menu");
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPreguntaActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombrePrueba.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Debes ingresar un nombre para la prueba.");
            return;
        }
        prueba.setNombre(nombre);

        CrearPreguntaPanel crearPregunta = new CrearPreguntaPanel(mainFrame, this, prueba);
        mainFrame.getMainPanel().add(crearPregunta, "crearPregunta");
        mainFrame.mostrarVista("crearPregunta");
    }//GEN-LAST:event_btnAgregarPreguntaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPregunta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNombrePrueba;
    // End of variables declaration//GEN-END:variables
}
