/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.PruebaController;
import Models.Opcion;
import Models.Pregunta;
import Models.Prueba;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Esteban
 */
public class CrearPreguntaPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private CrearPruebaPanel panelAnterior;
    private Prueba prueba;

    /**
     * Creates new form CrearPreguntaPanel
     */
    public CrearPreguntaPanel(MainFrame mainFrame, CrearPruebaPanel anterior, Prueba prueba) {
        this.mainFrame = mainFrame;
        this.panelAnterior = anterior;
        this.prueba = prueba;

        initComponents();
        panelOpcionesVF.setVisible(true);
        panelOpcionesMultiple.setVisible(false);
        btnAgregarPregunta.setEnabled(false);
        btnFinalizar.setEnabled(false);

        cmbTipoPregunta.addActionListener(e -> tipoSeleccionado());
        agregarListenersValidacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCorrecta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        btnAgregarPregunta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoPregunta = new javax.swing.JComboBox<>();
        cmbNivelBloom = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        panelOpcionesVF = new javax.swing.JPanel();
        rbVerdadero = new javax.swing.JRadioButton();
        panelOpcionesMultiple = new javax.swing.JPanel();
        txtOpt1 = new javax.swing.JTextField();
        rbCorrecta1 = new javax.swing.JCheckBox();
        txtOpt2 = new javax.swing.JTextField();
        rbCorrecta2 = new javax.swing.JCheckBox();
        txtOpt3 = new javax.swing.JTextField();
        rbCorrecta3 = new javax.swing.JCheckBox();
        txtOpt4 = new javax.swing.JTextField();
        rbCorrecta4 = new javax.swing.JCheckBox();

        jLabel1.setText("Enunciado");

        txtEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnunciadoActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnAgregarPregunta.setText("Agregar pregunta");
        btnAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPreguntaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo pregunta");

        cmbTipoPregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verdadero o falso", "Multiple" }));

        cmbNivelBloom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recordar", "Entender" }));

        jLabel3.setText("Nivel Bloom");

        rbVerdadero.setText("Verdadero");

        javax.swing.GroupLayout panelOpcionesVFLayout = new javax.swing.GroupLayout(panelOpcionesVF);
        panelOpcionesVF.setLayout(panelOpcionesVFLayout);
        panelOpcionesVFLayout.setHorizontalGroup(
            panelOpcionesVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesVFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbVerdadero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOpcionesVFLayout.setVerticalGroup(
            panelOpcionesVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesVFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbVerdadero)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        btnGroupCorrecta.add(rbCorrecta1);
        rbCorrecta1.setText("Correcta");

        btnGroupCorrecta.add(rbCorrecta2);
        rbCorrecta2.setText("Correcta");

        btnGroupCorrecta.add(rbCorrecta3);
        rbCorrecta3.setText("Correcta");

        btnGroupCorrecta.add(rbCorrecta4);
        rbCorrecta4.setText("Correcta");

        javax.swing.GroupLayout panelOpcionesMultipleLayout = new javax.swing.GroupLayout(panelOpcionesMultiple);
        panelOpcionesMultiple.setLayout(panelOpcionesMultipleLayout);
        panelOpcionesMultipleLayout.setHorizontalGroup(
            panelOpcionesMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesMultipleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesMultipleLayout.createSequentialGroup()
                        .addComponent(txtOpt1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbCorrecta1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesMultipleLayout.createSequentialGroup()
                        .addComponent(txtOpt2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbCorrecta2))
                    .addGroup(panelOpcionesMultipleLayout.createSequentialGroup()
                        .addComponent(txtOpt3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbCorrecta3))
                    .addGroup(panelOpcionesMultipleLayout.createSequentialGroup()
                        .addComponent(txtOpt4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbCorrecta4)))
                .addContainerGap())
        );
        panelOpcionesMultipleLayout.setVerticalGroup(
            panelOpcionesMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesMultipleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCorrecta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOpcionesMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCorrecta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOpcionesMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCorrecta3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOpcionesMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCorrecta4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOpcionesVF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarPregunta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbTipoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbNivelBloom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addComponent(panelOpcionesMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNivelBloom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOpcionesVF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOpcionesMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPregunta)
                    .addComponent(btnFinalizar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tipoSeleccionado() {
        String tipo = cmbTipoPregunta.getSelectedItem().toString();

        if (tipo.equalsIgnoreCase("Verdadero o falso")) {
            panelOpcionesVF.setVisible(true);
            panelOpcionesMultiple.setVisible(false);
        } else if (tipo.equalsIgnoreCase("Multiple")) {
            panelOpcionesVF.setVisible(false);
            panelOpcionesMultiple.setVisible(true);
        }

        revalidate();
        repaint();
    }

    private void agregarListenersValidacion() {
        txtEnunciado.getDocument().addDocumentListener(validar);
        cmbTipoPregunta.addActionListener(e -> validarCampos());
        cmbNivelBloom.addActionListener(e -> validarCampos());

        // VF
        rbVerdadero.addActionListener(e -> validarCampos());

        // MULTIPLE
        txtOpt1.getDocument().addDocumentListener(validar);
        txtOpt2.getDocument().addDocumentListener(validar);
        txtOpt3.getDocument().addDocumentListener(validar);
        txtOpt4.getDocument().addDocumentListener(validar);
        rbCorrecta1.addActionListener(e -> validarCampos());
        rbCorrecta2.addActionListener(e -> validarCampos());
        rbCorrecta3.addActionListener(e -> validarCampos());
        rbCorrecta4.addActionListener(e -> validarCampos());
    }

    private void validarCampos() {
        String enunciado = txtEnunciado.getText().trim();
        String tipo = (String) cmbTipoPregunta.getSelectedItem();
        String nivelBloom = (String) cmbNivelBloom.getSelectedItem();

        if (enunciado.isEmpty() || tipo == null || nivelBloom == null) {
            setBotones(false);
            return;
        }

        if (tipo.equals("Verdadero o falso")) {
            // Nada más que el enunciado y selección, no es necesario marcar nada (por defecto es Falso)
            setBotones(true);
            return;
        }

        // Si es MULTIPLE, verificar que haya 4 textos + 1 opción correcta seleccionada
        boolean opcionesLlenas
                = !txtOpt1.getText().trim().isEmpty()
                && !txtOpt2.getText().trim().isEmpty()
                && !txtOpt3.getText().trim().isEmpty()
                && !txtOpt4.getText().trim().isEmpty();

        int correctasSeleccionadas = 0;
        if (rbCorrecta1.isSelected()) {
            correctasSeleccionadas++;
        }
        if (rbCorrecta2.isSelected()) {
            correctasSeleccionadas++;
        }
        if (rbCorrecta3.isSelected()) {
            correctasSeleccionadas++;
        }
        if (rbCorrecta4.isSelected()) {
            correctasSeleccionadas++;
        }

        boolean unaCorrecta = correctasSeleccionadas == 1;

        setBotones(opcionesLlenas && unaCorrecta);
    }

    private void setBotones(boolean activo) {
        btnAgregarPregunta.setEnabled(activo);
        btnFinalizar.setEnabled(activo);
    }

    private final DocumentListener validar = new DocumentListener() {
        public void insertUpdate(DocumentEvent e) {
            validarCampos();
        }

        public void removeUpdate(DocumentEvent e) {
            validarCampos();
        }

        public void changedUpdate(DocumentEvent e) {
            validarCampos();
        }
    };

    private Pregunta crearPreguntaDesdeCampos() {
        Pregunta pregunta = new Pregunta();
        pregunta.setEnunciado(txtEnunciado.getText().trim());
        pregunta.setTipo(cmbTipoPregunta.getSelectedItem().toString().equals("Verdadero o falso") ? "VF" : "MULTIPLE");
        pregunta.setNivelBloom(cmbNivelBloom.getSelectedItem().toString());

        if (pregunta.getTipo().equals("VF")) {
            boolean correctoEsVerdadero = rbVerdadero.isSelected();
            pregunta.agregarOpcion(new Opcion("Verdadero", correctoEsVerdadero));
            pregunta.agregarOpcion(new Opcion("Falso", !correctoEsVerdadero));
        } else {
            pregunta.agregarOpcion(new Opcion(txtOpt1.getText().trim(), rbCorrecta1.isSelected()));
            pregunta.agregarOpcion(new Opcion(txtOpt2.getText().trim(), rbCorrecta2.isSelected()));
            pregunta.agregarOpcion(new Opcion(txtOpt3.getText().trim(), rbCorrecta3.isSelected()));
            pregunta.agregarOpcion(new Opcion(txtOpt4.getText().trim(), rbCorrecta4.isSelected()));
        }

        return pregunta;
    }
    


    private void txtEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnunciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnunciadoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        Pregunta p = crearPreguntaDesdeCampos();
        prueba.agregarPregunta(p);
        prueba.setFecha(new Date());

        PruebaController controller = new PruebaController();
        boolean ok = controller.guardarPrueba(prueba);

        if (ok) {
            JOptionPane.showMessageDialog(this, "✅ Prueba guardada correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al guardar la prueba.");
        }

        mainFrame.mostrarVista("menu");
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPreguntaActionPerformed
        // TODO add your handling code here:  
        
        Pregunta p = crearPreguntaDesdeCampos();
        prueba.agregarPregunta(p);

        CrearPreguntaPanel nuevo = new CrearPreguntaPanel(mainFrame, panelAnterior, prueba);
        mainFrame.getMainPanel().add(nuevo, "crearPregunta");
        mainFrame.mostrarVista("crearPregunta");
    }//GEN-LAST:event_btnAgregarPreguntaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPregunta;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.ButtonGroup btnGroupCorrecta;
    private javax.swing.JComboBox<String> cmbNivelBloom;
    private javax.swing.JComboBox<String> cmbTipoPregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelOpcionesMultiple;
    private javax.swing.JPanel panelOpcionesVF;
    private javax.swing.JCheckBox rbCorrecta1;
    private javax.swing.JCheckBox rbCorrecta2;
    private javax.swing.JCheckBox rbCorrecta3;
    private javax.swing.JCheckBox rbCorrecta4;
    private javax.swing.JRadioButton rbVerdadero;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtOpt1;
    private javax.swing.JTextField txtOpt2;
    private javax.swing.JTextField txtOpt3;
    private javax.swing.JTextField txtOpt4;
    // End of variables declaration//GEN-END:variables
}
