/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.Prueba;

/**
 *
 * @author Esteban
 */
public class ResultadoPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private double nota;
    private Prueba prueba;
    private java.util.List<String> respuestas;

    /**
     * Creates new form ResultadoPanel
     */
    public ResultadoPanel(MainFrame mainFrame, Prueba prueba, java.util.List<String> respuestas, double nota) {
        this.mainFrame = mainFrame;
        this.prueba = prueba;
        this.respuestas = respuestas;
        this.nota = nota;
        initComponents();

        notaResultado.setText("Tu nota es: " + String.format("%.1f", nota));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notaResultado = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JButton();
        btnRevisar = new javax.swing.JButton();

        notaResultado.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        notaResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notaResultado.setText("jLabel1");
        notaResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVolverMenu.setText("Terminar");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        btnRevisar.setText("Revisar");
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolverMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRevisar))
                    .addComponent(notaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(notaResultado)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolverMenu)
                    .addComponent(btnRevisar))
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:
        mainFrame.mostrarVista("menu");
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarActionPerformed
        // TODO add your handling code here:
        RevisarPruebaPanel revisar = new RevisarPruebaPanel(mainFrame, prueba, respuestas);
        mainFrame.getMainPanel().add(revisar, "revisarPrueba");
        mainFrame.mostrarVista("revisarPrueba");
    }//GEN-LAST:event_btnRevisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevisar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel notaResultado;
    // End of variables declaration//GEN-END:variables
}
