/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.Opcion;
import Models.Pregunta;
import Models.Prueba;
import java.awt.Color;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JRadioButton;

/**
 *
 * @author Esteban
 */
public class RevisarPruebaPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Prueba prueba;
    private List<String> respuestas;
    private int indice = 0;

    /**
     * Creates new form RevisarPruebaPanel
     */
    public RevisarPruebaPanel(MainFrame mainFrame, Prueba prueba, List<String> respuestas) {
        this.mainFrame = mainFrame;
        this.prueba = prueba;
        this.respuestas = respuestas;
        initComponents();

        panelOpciones.setLayout(new BoxLayout(panelOpciones, BoxLayout.Y_AXIS));
        mostrarPregunta(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enunciado = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        enunciado.setText("jLabel1");

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        btnAnterior.setText("jButton1");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("jButton2");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enunciado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(enunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents
private void mostrarPregunta(int index) {
        this.indice = index;
        Pregunta pregunta = prueba.getPreguntas().get(index);
        enunciado.setText((index + 1) + ". " + pregunta.getEnunciado());

        panelOpciones.removeAll();

        String respuestaUsuario = respuestas.get(index);

        for (Opcion o : pregunta.getOpciones()) {
            JRadioButton rb = new JRadioButton(o.getTexto());
            rb.setEnabled(false);

            boolean esCorrecta = o.isEsCorrecta();
            boolean seleccionada = o.getTexto().equals(respuestaUsuario);

            if (seleccionada) {
                rb.setSelected(true);
                if (esCorrecta) {
                    rb.setForeground(Color.GREEN);
                    rb.setText("✅ " + rb.getText());
                } else {
                    rb.setForeground(Color.RED);
                    rb.setText("❌ " + rb.getText());
                }
            } else if (esCorrecta) {
                rb.setForeground(new Color(0, 128, 0)); // verde oscuro
                rb.setText("✅ " + rb.getText());
            }

            panelOpciones.add(rb);
        }

        panelOpciones.revalidate();
        panelOpciones.repaint();

        btnAnterior.setEnabled(index > 0);
        btnAnterior.setText("Anterior");
        btnSiguiente.setText((index == prueba.getPreguntas().size() - 1) ? "Finalizar revisión" : "Siguiente");
    }

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here
        mostrarPregunta(indice - 1);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (indice == prueba.getPreguntas().size() - 1) {
            mainFrame.mostrarVista("menu");
        } else {
            mostrarPregunta(indice + 1);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel enunciado;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables
}
