/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.PruebaController;
import Models.Prueba;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class VerPruebasPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form verPruebasPanel
     */
    public VerPruebasPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0); // limpiar
        PruebaController controller = new PruebaController();
        List<Prueba> listaDePruebas = controller.listarPruebas();

        for (Prueba p : listaDePruebas) {
            System.out.println(p.getPreguntas());
            System.out.println(p.getCantidadPreguntas());
            modelo.addRow(new Object[]{p.getId(), p.getNombre(), p.getFecha(), p.getCantidadPreguntas(),  (p.getCantidadPreguntas() * 0.5) + "m" , "Iniciar"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha", "Número de preguntas", "Tiempo Estimado", "Acción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());

        if (col == 5) { // Columna "Acción"
            int pruebaId = (int) jTable1.getValueAt(row, 0);
            System.out.println("👉 Iniciar prueba con ID: " + pruebaId);
            Prueba prueba = new PruebaController().cargarPruebaCompleta(pruebaId); // este método lo creás
            AplicarPruebaPanel aplicarPrueba = new AplicarPruebaPanel(mainFrame, prueba);

            mainFrame.getMainPanel().add(aplicarPrueba, "aplicarPrueba");
            mainFrame.mostrarVista("aplicarPrueba");
            // Acá abrís el panel de aplicación de prueba (cuando lo tengas)
            // mainFrame.mostrarVista("aplicarPrueba");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        mainFrame.mostrarVista("menu");
    }//GEN-LAST:event_btnVolverActionPerformed
    public void recargarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        PruebaController controller = new PruebaController();
        List<Prueba> listaDePruebas = controller.listarPruebas();

        for (Prueba p : listaDePruebas) {
            modelo.addRow(new Object[]{p.getId(), p.getNombre(), p.getFecha(), p.getCantidadPreguntas(),  (p.getCantidadPreguntas() * 0.5) + "m" ,"Iniciar"});
        }
    }
    
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            recargarDatos();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
